#!/bin/bash

while true; do

	dwmweather > /home/peter/dwmscripts/dwmweather.txt

	sleep 3600s

done &

while true; do

	SUN=$(dwmweather)
	VOL=$(dwmvol)
	CPU=$(dwmcpu)
	MEM=$(dwmmem)
	NET=$(dwmtraf)
	TEMP=$(dwmtemp)
	HDD=$(dwmdisk)
	TIME=$(dwmclock)
	xsetroot -name "| SUN | $CPU | $MEM | $NET | $TEMP | $HDD | $VOL | $TIME"

	sleep 5s

	
done &
